version: "3.9"

services:
  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - my-vol:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: omkar123
      MYSQL_DATABASE: student_db
   

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_NAME: student_db
      DB_PASSWD: omkar123
      DB_USERNAME: root
      HOST_NAME: database
    depends_on:
      - database
        
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      HOST_IP: 3.110.105.15
    depends_on:
      - backend

volumes:
  my-vol: