apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studentapp-ingress
  labels:
    app: studentapp
spec:
  ingressClassName: nginx
  rules:
  - host: a76141c88b8734edc972a5dacf76699e-938877814.ap-south-1.elb.amazonaws.com 
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: studentapp-frontend-svc
            port: 
              number: 80
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: studentapp-backend-svc
            port: 
              number: 8080      